apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{app}-route-debug-helper"
  namespace: "{namespace}"
spec:
  host: "{debug_helper_url}"
  subdomain: ''
  to:
    kind: Service
    name: "{app}"
    weight: 100
  port:
    targetPort: 12424
  wildcardPolicy: None
status:
  ingress:
    - host: "{debug_helper_url}"
