apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{id}}"
  labels:
    name: "{{name}}"
    type: gucconnector
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: "{{name}}"
        spec:
          restartPolicy: Never
          containers:
          - name: "{{name}}"
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
            image: "{{image}}"
            imagePullPolicy: IfNotPresent
            env:
              - "{{env_vars}}"